name: "Run fedora-review"

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: docker
    container:
      image: fedora:43

      # https://pagure.io/FedoraReview/issue/541
      options: --privileged

    steps:
      - name: Clone the repository
        uses: actions/checkout@v6

      - name: Run local fedora-review action
        uses: ./.forgejo/actions/fedora-review
        with:
          spec: test/light.spec
          name: light
