name: 'Fedora Review'
author: 'FrostyX'
description: |
  Run fedora-review on every commit.

inputs:
  spec:
    description: 'A path to the spec file'

  name:
    description: 'The name of the package'

outputs:
  time:
    description: 'The time when the action was run'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: dnf -y install rpmbuild fedora-review jq
      shell: bash

    - name: Create a tmp directory
      run: mkdir /tmp/fedora-review
      shell: bash

    # In the future we will probably download the spec, SRPM and RPM files
    # from Koji scratch build, which would be a pre-requisite workflow.
    # That way we will avoid wasting resources and make this action much faster
    # for large packages.

    - name: Copy spec to the tmp directory
      run: cp ${{ inputs.spec }} /tmp/fedora-review
      shell: bash

    # Use fedpkg once we are in the DistGit
    - name: Build SRPM from the spec file
      run: >
        rpmbuild -bs ${{ inputs.spec }}
        -D "%_disable_source_fetch 0"
        -D "%_sourcedir /tmp/fedora-review"
        -D "%_specdir /tmp/fedora-review"
        -D "%_srcrpmdir /tmp/fedora-review"
      shell: bash

    # TODO Implement fedora-review -X for skipping whole sections/groups of checks
    # https://pagure.io/FedoraReview/pull-request/542
    # Then we will skip SHOULD and EXTRA sections
    # We want this only for performance reasons, it's not a hard requirement.
    # We already filter out the unwanted section when parsing `review.json`.
    - name: Run fedora-review
      run: >
        fedora-review -n ${{ inputs.name }}
        -x CheckNoNameConflict
      shell: bash
      working-directory: /tmp/fedora-review
      env:
        REVIEW_NO_MOCKGROUP_CHECK: true

    # TODO Work with all MUST subsections, not only Generic
    - name: Count failed MUST items
      id: count_must_items
      run: cat /tmp/fedora-review/review-${{ inputs.name }}/review.json |jq '[.results.MUST.Generic[] | select(.result == "fail")] |length' |awk '{OFS=""; print "count=", $0 }' >> $GITHUB_OUTPUT
      shell: bash

    # TODO Work with all MUST subsections, not only Generic
    # TODO Show these in the Web UI as this is the most important output for the user
    - name: Print failed checks
      if: steps.count_must_items.outputs.count != 0
      run: cat /tmp/fedora-review/review-${{ inputs.name }}/review.json |jq '[.results.MUST.Generic[] | select(.result == "fail")]'
      shell: bash

    # TODO Show a user friendly message
    - name: Make sure no check failed
      run: test "${{ steps.count_must_items.outputs.count }}" -eq 0
      shell: bash
